#include <Arduino.h>
#include "utility/dspinst.h"
#include "AudioStream.h"

#ifdef AIC3204
#include "codec/AIC3204/AudioOutputI2S.h"
#include "codec/AIC3204/AudioInputI2S.h"
#include "codec/AIC3204/I2SBridge.h"
#endif

#ifdef PCM5102
#include "codec/PCM5102/AudioOutputI2S.h"
#endif

#include "analyze_print.h"
#include "analyze_tonedetect.h"
#include "analyze_notefreq.h"
#include "analyze_peak.h"
#include "analyze_rms.h"
#include "effect_bitcrusher.h"
#include "effect_chorus.h"
#include "effect_fade.h"
#include "effect_flange.h"
#include "effect_envelope.h"
#include "effect_multiply.h"
#include "effect_delay.h"
#include "effect_midside.h"
#include "effect_reverb.h"
#include "effect_freeverb.h"
#include "effect_waveshaper.h"
#include "effect_granular.h"
#include "effect_combine.h"
#include "effect_rectifier.h"
#include "effect_wavefolder.h"
#include "filter_biquad.h"
#include "filter_fir.h"
#include "filter_variable.h"
#include "filter_ladder.h"
#include "mixer.h"
#include "play_memory.h"
#include "play_queue.h"
#include "synth_tonesweep.h"
#include "synth_sine.h"
#include "synth_waveform.h"
#include "synth_dc.h"
#include "synth_whitenoise.h"
#include "synth_pinknoise.h"
#include "synth_karplusstrong.h"
#include "synth_simple_drum.h"
#include "synth_pwm.h"
#include "synth_wavetable.h"